### ISSUE TITLE
Create a Join House/Create User page

### ISSUE THREAD

**Issue by Decoder22** [PurdueHCR/Firestore#11]
# Tasks
- [ ] Create the UI for the Join House Page
- [ ] Create the files required for the BLoC
- [ ] Add a BloC to the page that handles events for Join House and Loggout
- [ ] Use a BlocBuilder to display appropriate Widgets for the InitializationState, LoadingState, and PageLoadedState

## UI Design
The overall design should look similar to the login and create account cards. Widgets include:
0. BlocBuilder using AuthenticationBLoC
1. Text Field for their First Name
2. Text Field for their Last Name
3. Text Field for House Code
4. Button for Join House - Add JoinHouse event to authBloc
5. Button for Log out
6. Error message Texts under fields. (hidden unless error)
7. Loading symbol (hidden unless the state is loading. All other widgets should not display)

## Join House BLoC
The join house bloc needs to handle events from the page and call the endpoint to create a user. (Check the [api documentation](https://purdue-hcr-test.web.app/api/#/user/post_user_create) for the route) 

## Bloc Events
1. JoinHouse(firstname, lastname, housecode) 
  - Call event when the Join House button is pressed. 
  - Handles Validation errors (make sure house code is exactly 6 digits and first name length < 20 and last name length < 20
2. Loggout
  - Call AuthenticationBloc to loggout
