### ISSUE TITLE
Update POST /events/ endpoint

### ISSUE THREAD

**Issue by Decoder22** [PurdueHCR/Firestore#90]
### Description
This task is about updating the existing endpoint to our API's Standards (parsing the body with Parameter Parse and moving complex logic to another file) and modifying the logic to support the changes to the Create Event process.

## Endpoint Description
Posting to `/events/ ` will create a new event from the details provided in the body. This EP will verify that the requesting user has the correct permissions, verify that all required fields were provided in the body, confirm that the user has the ability to create events with the provided point type id, create the event, and respond with 200 when the event was created.

### Todo
- [ ] Redo the src/endpoint_paths/event.ts : `/add` endpoint to just be `/` 
- [ ] Rearrange the try catch to encompass the entire section and handle the error responses in the catch statement
- [ ] Parse the body for all fields using the Parameter Parser. Do not throw an error for a field that is not required
- [ ] Move all logic into a file called src/src/CreateEvent.ts
- [ ] Create Tests
