### ISSUE TITLE
Create PUT /events/ endpoint

### ISSUE THREAD

**Issue by Decoder22** [PurdueHCR/Firestore#91]
### Description
This task is about creating an endpoint to update an event.

## Endpoint Description
PUTting to `/events/ ` will update an existing event with the details provided in the body. This EP will verify that the requesting user has the correct permissions, verify that all required fields were provided in the body, confirm that the user has the permission to update that event, confirm the user has the permissions to update the event with the provided data(specifically check that they have access to the point type id if one was provided), update the event, and respond with 200 when the event was updated.

### Todo
- [ ] Create in src/endpoint_paths/event.ts a PUT endpoint `/`
- [ ] Parse the body for the required field 'Id' and any optional fields
- [ ] If there are no fields to update, return a 200 response
- [ ] If a new pointTypeId is provided, verify that the user has the ability to create an event with that Point Type Id.
- [ ] Verify dates are valid
- [ ] If all fields are valid, update the event and respond in a 200 response
